baseURL = "https://bingguanghao.github.io"
languageCode = "en-us"
title = "Agent"
theme = "ananke"

DefaultContentLanguage = "en"
SectionPagesMenu = "main"
pagination.pagerSize  = 3                  # this is set low for demonstrating with dummy content. Set to a higher number
googleAnalytics = ""
enableRobotsTXT = true

[languages]
[languages.en]
title = "Agent"
weight = 1
contentDir = "content/en"
# languageDirection = 'rtl' for Right-To-Left languages
#[languages.fr]
#title = "Ananke Fr"
#weight = 2
#contentDir = "content/fr"

[sitemap]
changefreq = "monthly"
priority = 0.5
filename = "sitemap.xml"

[params]
text_color = ""
author = ""
favicon = ""
site_logo = "/images/antgroup.png"
# description = "The last theme you'll ever need. Maybe."
# choose a background color from any on this page: https://tachyons.io/docs/themes/skins/ and preface it with "bg-"
background_color_class = "bg-black"
recent_posts_number = 3